nota1 = input("Digite a primeira nota: ")
nota2 = input("Digite a segunda nota: ")
nota3 = input("Digite a terceira nota: ")
nota4 = input("Digite a quarta nota: ")
temp1 = int(nota1)
temp2 = int(nota2)
temp3 = int(nota3)
temp4 = int(nota4)
mediaAritmet = (temp1 + temp2 + temp3 + temp4) / 4
print ("A média aritmética é", mediaAritmet)